# Generated by Django 3.1.7 on 2021-11-17 15:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ProductsApp', '0003_productmodel'),
    ]

    operations = [
        migrations.DeleteModel(
            name='productmodel',
        ),
    ]
