# Generated by Django 3.1.7 on 2021-11-17 16:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('UserApp', '0003_postmodel_usermodel'),
    ]

    operations = [
        migrations.DeleteModel(
            name='postmodel',
        ),
        migrations.DeleteModel(
            name='usermodel',
        ),
    ]
